"""Adição de novos objetos e atulização de objetos já existentes.

Revision ID: 34610e4ac669
Revises: 21f0e465068c
Create Date: 2026-06-09 22:36:03.065997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34610e4ac669'
down_revision: Union[str, Sequence[str], None] = '21f0e465068c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_id', sa.UUID(), nullable=False))
    op.alter_column('accounts', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.drop_column('accounts', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('accounts', 'balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('accounts', 'account_id')
    # ### end Alembic commands ###
